-- ============================================
-- Migration: 044_sensor_device_type
--
-- Add 'sensor' device type to support temperature sensors,
-- humidity sensors, fuel level sensors, and other monitoring devices.
-- ============================================

-- Update device_templates constraint to include 'sensor'
-- The constraint name is auto-generated by PostgreSQL as 'device_templates_device_type_check'
ALTER TABLE device_templates
  DROP CONSTRAINT IF EXISTS device_templates_device_type_check;

ALTER TABLE device_templates
  ADD CONSTRAINT device_templates_device_type_check
  CHECK (device_type IN ('inverter', 'dg', 'load_meter', 'sensor'));

-- Also update the operation constraint to allow 'sensor' operation
-- This maps sensor device types to sensor operation for the controller
ALTER TABLE device_templates
  DROP CONSTRAINT IF EXISTS device_templates_operation_check;

ALTER TABLE device_templates
  ADD CONSTRAINT device_templates_operation_check
  CHECK (operation IN ('solar', 'dg', 'meter', 'sensor'));
