"use client";

/**
 * Step 5: Cloud Connection
 *
 * Explains that configuration is generated automatically by the setup script.
 * Shows a preview of what config will be generated.
 * Verifies that the controller was successfully registered during setup.
 */

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

interface StepCloudConnectionProps {
  controllerId: string | null;
  serialNumber: string;
  onConfirm: (confirmed: boolean) => void;
  confirmed: boolean;
}

interface RegistrationStatus {
  verified: boolean;
  loading: boolean;
  message: string;
  status?: string;
}

export function StepCloudConnection({
  controllerId,
  serialNumber,
  onConfirm,
  confirmed,
}: StepCloudConnectionProps) {
  const supabase = createClient();
  const [registration, setRegistration] = useState<RegistrationStatus>({
    verified: false,
    loading: true,
    message: "Checking registration status...",
  });

  // Verify controller registration on mount
  useEffect(() => {
    const verifyRegistration = async () => {
      if (!controllerId) {
        setRegistration({
          verified: false,
          loading: false,
          message: "Controller ID not available",
        });
        return;
      }

      try {
        const { data: controller, error } = await supabase
          .from("controllers")
          .select("id, serial_number, status, created_at")
          .eq("id", controllerId)
          .single();

        if (error || !controller) {
          setRegistration({
            verified: false,
            loading: false,
            message: "Controller not found in database. Setup script may not have completed registration.",
          });
          return;
        }

        // Check if controller has a serial number (indicates setup script ran)
        if (!controller.serial_number) {
          setRegistration({
            verified: false,
            loading: false,
            message: "Controller exists but serial number not set. Setup script may not have completed.",
            status: controller.status,
          });
          return;
        }

        setRegistration({
          verified: true,
          loading: false,
          message: `Registered: ${controller.serial_number} (${controller.status})`,
          status: controller.status,
        });
      } catch (err) {
        console.error("Error verifying registration:", err);
        setRegistration({
          verified: false,
          loading: false,
          message: "Error checking registration status",
        });
      }
    };

    verifyRegistration();
  }, [controllerId, supabase]);
  // Show example config preview (actual values are generated by setup script)
  const configPreview = `# Volteria Controller Configuration
# Auto-generated by setup script - DO NOT EDIT MANUALLY

controller:
  id: "${controllerId || '<auto-generated>'}"
  serial_number: "${serialNumber || '<detected-from-pi>'}"

cloud:
  supabase_url: "https://xxx.supabase.co"
  supabase_key: "eyJhbG..."
  sync_interval_s: 300  # Config sync every 5 minutes

services:
  system:
    heartbeat_interval_s: 30
    health_check_interval_s: 10
  logging:
    local_write_interval_s: 10
    cloud_sync_interval_s: 120

ssh:
  tunnel_port: <assigned-by-cloud>
  central_server: "159.223.224.203"`;

  return (
    <div className="space-y-6">
      {/* Registration Status */}
      {registration.loading ? (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex gap-3 items-center">
            <div className="w-5 h-5 border-2 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
            <p className="text-sm text-blue-700">{registration.message}</p>
          </div>
        </div>
      ) : registration.verified ? (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <div className="flex gap-3">
            <svg className="w-6 h-6 text-green-600 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <div>
              <h3 className="font-medium text-green-800 mb-1">Registration Verified</h3>
              <p className="text-sm text-green-700">{registration.message}</p>
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
          <div className="flex gap-3">
            <svg className="w-6 h-6 text-amber-600 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <div>
              <h3 className="font-medium text-amber-800 mb-1">Registration Pending</h3>
              <p className="text-sm text-amber-700">{registration.message}</p>
              <p className="text-xs text-amber-600 mt-2">
                Make sure you ran the setup script from Step 2 on your Raspberry Pi.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Main info message */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div className="flex gap-3">
          <svg className="w-6 h-6 text-blue-600 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div>
            <h3 className="font-medium text-blue-800 mb-1">Automatic Configuration</h3>
            <p className="text-sm text-blue-700">
              The setup script you ran in Step 2 configures the cloud connection automatically.
              No manual configuration needed.
            </p>
          </div>
        </div>
      </div>

      {/* How it works */}
      <div className="space-y-4">
        <h4 className="font-medium">How automatic configuration works:</h4>

        <div className="space-y-3">
          {/* Step 1 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              1
            </div>
            <div>
              <h5 className="font-medium text-sm">Setup script detects Pi serial number</h5>
              <p className="text-xs text-muted-foreground mt-1">
                The script reads: <code className="bg-muted px-1 rounded">cat /proc/cpuinfo | grep Serial</code>
              </p>
            </div>
          </div>

          {/* Step 2 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              2
            </div>
            <div>
              <h5 className="font-medium text-sm">Registers with Volteria cloud</h5>
              <p className="text-xs text-muted-foreground mt-1">
                Calls our API to register the Pi and get cloud credentials
              </p>
            </div>
          </div>

          {/* Step 3 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              3
            </div>
            <div>
              <h5 className="font-medium text-sm">Generates config automatically</h5>
              <p className="text-xs text-muted-foreground mt-1">
                Creates <code className="bg-muted px-1 rounded">/etc/volteria/config.yaml</code> with all required settings
              </p>
            </div>
          </div>

          {/* Step 4 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              4
            </div>
            <div>
              <h5 className="font-medium text-sm">5 services start automatically</h5>
              <p className="text-xs text-muted-foreground mt-1">
                System, config, device, control, and logging services are enabled
              </p>
            </div>
          </div>

          {/* Step 5 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              5
            </div>
            <div>
              <h5 className="font-medium text-sm">SSH tunnel established</h5>
              <p className="text-xs text-muted-foreground mt-1">
                Reverse SSH tunnel connects to central server for remote access
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Default Network Settings */}
      <div className="space-y-2">
        <h4 className="font-medium flex items-center gap-2">
          <svg className="w-4 h-4 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
          </svg>
          Default Network Settings
        </h4>
        <p className="text-xs text-muted-foreground">
          The setup script configures the following network settings automatically:
        </p>
        <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 space-y-4">
          {/* Ethernet Settings */}
          <div>
            <div className="flex items-center gap-2 mb-2">
              <svg className="w-4 h-4 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2" />
              </svg>
              <span className="font-medium text-sm">Ethernet (eth0) - Static IP</span>
            </div>
            <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs ml-6">
              <div className="text-muted-foreground">IP Address:</div>
              <div className="font-mono font-medium">192.168.1.100</div>
              <div className="text-muted-foreground">Gateway:</div>
              <div className="font-mono font-medium">192.168.1.1</div>
              <div className="text-muted-foreground">Subnet Mask:</div>
              <div className="font-mono font-medium">255.255.255.0</div>
              <div className="text-muted-foreground">DNS Servers:</div>
              <div className="font-mono font-medium">8.8.8.8, 8.8.4.4</div>
            </div>
          </div>
          {/* WiFi Settings */}
          <div className="border-t border-slate-200 pt-3">
            <div className="flex items-center gap-2 mb-2">
              <svg className="w-4 h-4 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.14 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0" />
              </svg>
              <span className="font-medium text-sm">WiFi (wlan0) - DHCP</span>
            </div>
            <p className="text-xs text-muted-foreground ml-6">
              WiFi is configured via Raspberry Pi Imager (Step 2). The controller will obtain an IP address automatically via DHCP when connected to your WiFi network.
            </p>
          </div>
        </div>
        <p className="text-xs text-amber-600">
          Note: If your network uses a different IP range (e.g., 10.x.x.x or 172.x.x.x), you may need to manually adjust the static IP after setup.
        </p>
      </div>

      {/* Config preview */}
      <div className="space-y-2">
        <h4 className="font-medium flex items-center gap-2">
          <svg className="w-4 h-4 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Configuration Preview
        </h4>
        <p className="text-xs text-muted-foreground">
          This is what the auto-generated config looks like:
        </p>
        <div className="scroll-fade-right">
          <pre className="bg-muted p-4 rounded-lg text-xs overflow-x-auto font-mono max-w-full">
            {configPreview}
          </pre>
        </div>
      </div>

      {/* Cloud-first note */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div className="flex gap-3">
          <svg className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
          </svg>
          <div>
            <h4 className="font-medium text-blue-800">Minimal Bootstrap Configuration</h4>
            <p className="text-sm text-blue-700">
              The local config only contains the controller ID and cloud credentials needed to connect to the platform.
              Once this controller is assigned to a site, it will automatically fetch and cache all site settings
              (devices, control parameters, thresholds) for local operation.
            </p>
          </div>
        </div>
      </div>

      {/* What's next */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
        <div className="flex gap-3">
          <svg className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
          </svg>
          <div>
            <h4 className="font-medium text-amber-800">What&apos;s Next</h4>
            <p className="text-sm text-amber-700">
              In the next step, we&apos;ll verify that the controller is online and sending heartbeats.
              This confirms the cloud connection is working correctly.
            </p>
          </div>
        </div>
      </div>

      {/* Confirmation checkbox */}
      <label className="flex items-center gap-3 p-4 border rounded-lg cursor-pointer hover:bg-muted/50">
        <input
          type="checkbox"
          checked={confirmed}
          onChange={(e) => onConfirm(e.target.checked)}
          className="w-5 h-5 rounded border-gray-300"
        />
        <span className="text-sm">
          I understand that configuration was generated automatically by the setup script
        </span>
      </label>
    </div>
  );
}
