"use client";

/**
 * Step 5: Cloud Connection
 *
 * Explains that configuration is generated automatically by the setup script.
 * Shows a preview of what config will be generated.
 */

interface StepCloudConnectionProps {
  controllerId: string | null;
  serialNumber: string;
  onConfirm: (confirmed: boolean) => void;
  confirmed: boolean;
}

export function StepCloudConnection({
  controllerId,
  serialNumber,
  onConfirm,
  confirmed,
}: StepCloudConnectionProps) {
  // Show example config preview (actual values are generated by setup script)
  const configPreview = `# Volteria Controller Configuration
# Auto-generated by setup script - DO NOT EDIT MANUALLY

controller:
  id: "${controllerId || '<auto-generated>'}"
  serial_number: "${serialNumber || '<detected-from-pi>'}"

cloud:
  supabase_url: "https://xxx.supabase.co"
  supabase_key: "eyJhbG..."
  sync_enabled: true`;

  return (
    <div className="space-y-6">
      {/* Main success message */}
      <div className="bg-green-50 border border-green-200 rounded-lg p-4">
        <div className="flex gap-3">
          <svg className="w-6 h-6 text-green-600 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div>
            <h3 className="font-medium text-green-800 mb-1">Automatic Configuration</h3>
            <p className="text-sm text-green-700">
              The setup script you ran in Step 2 has already configured the cloud connection!
              No manual configuration needed.
            </p>
          </div>
        </div>
      </div>

      {/* How it works */}
      <div className="space-y-4">
        <h4 className="font-medium">How automatic configuration works:</h4>

        <div className="space-y-3">
          {/* Step 1 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              1
            </div>
            <div>
              <h5 className="font-medium text-sm">Setup script detects Pi serial number</h5>
              <p className="text-xs text-muted-foreground mt-1">
                The script reads: <code className="bg-muted px-1 rounded">cat /proc/cpuinfo | grep Serial</code>
              </p>
            </div>
          </div>

          {/* Step 2 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              2
            </div>
            <div>
              <h5 className="font-medium text-sm">Registers with Volteria cloud</h5>
              <p className="text-xs text-muted-foreground mt-1">
                Calls our API to register the Pi and get cloud credentials
              </p>
            </div>
          </div>

          {/* Step 3 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              3
            </div>
            <div>
              <h5 className="font-medium text-sm">Generates config automatically</h5>
              <p className="text-xs text-muted-foreground mt-1">
                Creates <code className="bg-muted px-1 rounded">/etc/volteria/config.yaml</code> with all required settings
              </p>
            </div>
          </div>

          {/* Step 4 */}
          <div className="flex gap-4 p-4 border rounded-lg">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-700 rounded-full flex items-center justify-center font-bold text-sm">
              4
            </div>
            <div>
              <h5 className="font-medium text-sm">Service starts automatically</h5>
              <p className="text-xs text-muted-foreground mt-1">
                The volteria-controller service is enabled and started
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Config preview */}
      <div className="space-y-2">
        <h4 className="font-medium flex items-center gap-2">
          <svg className="w-4 h-4 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Configuration Preview
        </h4>
        <p className="text-xs text-muted-foreground">
          This is what the auto-generated config looks like:
        </p>
        <div className="scroll-fade-right">
          <pre className="bg-muted p-4 rounded-lg text-xs overflow-x-auto font-mono max-w-full">
            {configPreview}
          </pre>
        </div>
      </div>

      {/* Cloud-first note */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div className="flex gap-3">
          <svg className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
          </svg>
          <div>
            <h4 className="font-medium text-blue-800">Cloud-First Configuration</h4>
            <p className="text-sm text-blue-700">
              The local config only contains the controller ID and cloud credentials.
              All other settings (site assignment, devices, control settings) are managed
              through this platform and fetched automatically by the controller.
            </p>
          </div>
        </div>
      </div>

      {/* What's next */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
        <div className="flex gap-3">
          <svg className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
          </svg>
          <div>
            <h4 className="font-medium text-amber-800">What&apos;s Next</h4>
            <p className="text-sm text-amber-700">
              In the next step, we&apos;ll verify that the controller is online and sending heartbeats.
              This confirms the cloud connection is working correctly.
            </p>
          </div>
        </div>
      </div>

      {/* Confirmation checkbox */}
      <label className="flex items-center gap-3 p-4 border rounded-lg cursor-pointer hover:bg-muted/50">
        <input
          type="checkbox"
          checked={confirmed}
          onChange={(e) => onConfirm(e.target.checked)}
          className="w-5 h-5 rounded border-gray-300"
        />
        <span className="text-sm">
          I understand that configuration was generated automatically by the setup script
        </span>
      </label>
    </div>
  );
}
